fix: update test-apps gh action

diff --git a/.github/workflows/test-apps.yml b/.github/workflows/test-apps.yml
--- a/.github/workflows/test-apps.yml
+++ b/.github/workflows/test-apps.yml
@@ -13,12 +13,21 @@ jobs:
 
             - name: Install dependencies and run tests
               run: |
-                  for dir in apps/*; do               # Iterate over each folder in /apps
-                    if [ -d "$dir" ]; then            # Check if it's a directory
+                  # Save the current working directory
+                  original_dir=$(pwd)
+
+                  # Absolute path to the 'apps' directory
+                  apps_dir="$original_dir/apps"
+
+                  # Iterate over each folder in /apps
+                  for dir in "$apps_dir"/*; do
+                    if [ -d "$dir" ]; then
                       echo "Running yarn in $dir"
-                      cd "$dir"                       # Navigate to the directory
-                      yarn                             # Run yarn to install dependencies
-                      yarn test                       # Run yarn test to execute tests
-                      cd ..                           # Navigate back to the /apps directory
+                      # Navigate to the directory using absolute path
+                      cd "$dir" || exit 1  # Exit if cd fails
+                      yarn  # Run yarn to install dependencies
+                      yarn test  # Run yarn test to execute tests
+                      # Return to the original directory using absolute path
+                      cd "$original_dir" || exit 1  # Exit if cd fails
                     fi
                   done
